### PR TITLE
Bug fixes

### LINKED ISSUE #212: Convert file size for Media to KB, MB and so on
We could may be use the function mentioned in the solution here: https://stackoverflow.com/questions/15900485/correct-way-to-convert-size-in-bytes-to-kb-mb-gb-in-javascript

### LINKED ISSUE #264: Add ability to delete uploaded images
- [ ] DegaUser
- [ ] Rating
- [ ] Claimant

check images in the other entities as well.

### LINKED ISSUE #283: Unable to add Mobile Icon in Organization

### LINKED ISSUE #287: Media upload dialog doesn't let you add new images directly

### LINKED ISSUE #289: Core and Factcheck menu items should not be visible on homepage when use is not logged in yet

### PR DESCRIPTION
**Pull request by rahuljaisinghani**
closes: #212 
closes: #283 
closes #264
closes #287 
closes #289

### CODE REVIEW

File: src/main/webapp/app/entities/core/media/media-detail.component.ts [hunk 1]
```diff
@@ -1,6 +1,6 @@
 import { Component, OnInit } from '@angular/core';
 import { ActivatedRoute } from '@angular/router';
-
+import { Pipe, PipeTransform } from '@angular/core';
```
Comment (arghyaiitb) [inline src/main/webapp/app/entities/core/media/media-detail.component.ts]: is it required?

File: src/main/webapp/app/entities/core/post/post-update.component.ts [hunk 2]
```diff
@@ -152,7 +152,6 @@ export class PostUpdateComponent implements OnInit {
             categories: [this.post.categories], // convert into this.fb.array
             tags: [this.post.tags], // convert into this.fb.array
             degaUsers: [this.post.degaUsers || '', Validators.required], // convert into this.fb.array
-            clientId: [this.post.clientId || ''], // delete once backend is fixed
             publishedDate: [this.post.publishedDate || null], // delete once backend is fixed
```
Comment (arghyaiitb) [inline src/main/webapp/app/entities/core/post/post-update.component.ts:155]: delete this also

File: src/main/webapp/app/entities/core/post/post-update.component.ts [hunk 3]
```diff
@@ -152,7 +152,6 @@ export class PostUpdateComponent implements OnInit {
...
             createdDate: [this.post.createdDate || null] // delete once backend is fixed
```
Comment (arghyaiitb) [inline src/main/webapp/app/entities/core/post/post-update.component.ts:156]: delete this and check if it is working, if things are breaking then keep it as it is

File: src/main/webapp/app/entities/factcheck/rating/rating-update.component.html [hunk 4]
```diff
@@ -82,6 +82,14 @@ <h2 id="jhi-rating-heading" jhiTranslate="gatewayApp.factcheckRating.home.create
                             Upload Rating Icon
                         </span>
                     </button>
+                    <button *ngIf="rating.media != null" mat-raised-button color="warn"
+                    id="field_iconURL" class="btn btn-primary jh-create-entity create-media"
```
Comment (arghyaiitb) [inline src/main/webapp/app/entities/factcheck/rating/rating-update.component.html]: `id="field_iconURL"` rename it

File: src/main/webapp/app/shared/quill-editor/quill-editor-file-upload.component.html [hunk 5]
```diff
@@ -19,7 +19,7 @@ <h2 class="jhi-claim-heading">Featured Media <mat-icon class="float-right" data-
                         <fa-icon [icon]="'trash-alt'"></fa-icon>
                     </button>
                     <div class="mat-file-upload">
-                        <button mat-raised-button color="primary">Upload Media <mat-icon>attach_file</mat-icon></button>
+                        <button mat-raised-button color="primary" (click)="fileInput.click()">Upload Media <mat-icon>attach_file</mat-icon></button>
```
Comment (arghyaiitb) [inline src/main/webapp/app/shared/quill-editor/quill-editor-file-upload.component.html:22]: what is this ?

File: src/main/webapp/app/entities/factcheck/rating/rating-update.component.ts [hunk 6]
```diff
@@ -116,4 +116,8 @@ export class RatingUpdateComponent implements OnInit {
     showClientIdField(degausersRole: String): boolean {
         return ADMIN_ROLE.includes(degausersRole);
     }
+
+    deleteMediaForFeature() {
```
Comment (arghyaiitb) [inline src/main/webapp/app/entities/factcheck/rating/rating-update.component.ts]: rename function

File: src/main/webapp/app/entities/factcheck/claimant/claimant-update.component.ts [hunk 7]
```diff
@@ -80,4 +80,8 @@ export class ClaimantUpdateComponent implements OnInit {
     updateMediaForFeature(imageData) {
         this.claimant.media = imageData;
     }
+
+    deleteMediaForFeature() {
```
Comment (arghyaiitb) [inline src/main/webapp/app/entities/factcheck/claimant/claimant-update.component.ts]: rename function

**Review by arghyaiitb — APPROVED** [review]
